/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./components/Dashboard/BarChart.vue')['default']
    Filters: typeof import('./components/Dashboard/Filters.vue')['default']
    PriceReferenceCard: typeof import('./components/Dashboard/PriceReferenceCard.vue')['default']
    ProductCard: typeof import('./components/Dashboard/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeLineChart: typeof import('./components/Dashboard/TimeLineChart.vue')['default']
  }
}
